import {
  v4 as uuid
} from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [{
    // TSHIRTS
    _id: uuid(),
    name: "Nob Head Oversized T-Shirt",
    image: "",
    price: 999,
    category: "tshirt",
    discountPercentage: "30%",
    discountPrice: 699,
    inStock: true,
    rating: 3.9,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
  },
  {
    _id: uuid(),
    name: "Untamed Faded Effect Oversized T-Shirt",
    image: "",
    price: 999,
    category: "tshirt",
    discountPercentage: "30%",
    discountPrice: 699,
    inStock: true,
    rating: 3.9,
    desc: " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
  },
  {
    _id: uuid(),
    name: "Motordrip Faded Effect Oversized T-shirt",
    image: "",
    price: 999,
    category: "tshirt",
    discountPercentage: "30%",
    discountPrice: 699,
    inStock: true,
    rating: 3.9,
    desc: " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
  },
  {
    _id: uuid(),
    name: "Signature Baller Oversized Jersey Set",
    image: "",
    price: 999,
    category: "tshirt",
    discountPercentage: "30%",
    discountPrice: 699,
    inStock: true,
    rating: 3.9,
    desc: " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
  },
  // BOTTOMS
  {
    _id: uuid(),
    name: "Jade Joggers",
    image: "",
    price: 999,
    category: "bottoms",
    discountPercentage: "30%",
    discountPrice: 699,
    inStock: true,
    rating: 3.9,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
  },
  {
    _id: uuid(),
    name: "Little Snitch Black Joggers",
    image: "",
    price: 999,
    category: "bottoms",
    discountPercentage: "30%",
    discountPrice: 699,
    inStock: true,
    rating: 3.9,
    desc: " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
  },
  {
    _id: uuid(),
    name: "Maroon Utility Straight Fit Pants",
    image: "",
    price: 999,
    category: "bottoms",
    discountPercentage: "30%",
    discountPrice: 699,
    inStock: true,
    rating: 3.9,
    desc: " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
  },
  {
    _id: uuid(),
    name: "Black Utility Straight Fit Pant",
    image: "",
    price: 999,
    category: "bottoms",
    discountPercentage: "30%",
    discountPrice: 699,
    inStock: true,
    rating: 3.9,
    desc: " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
  },
  // JACKETS
  {
    _id: uuid(),
    name: "Matcha Oversized Zipper",
    image: "",
    price: 999,
    category: "jacket",
    discountPercentage: "30%",
    discountPrice: 699,
    inStock: true,
    rating: 3.9,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
  },
  {
    _id: uuid(),
    name: "Brown Oversized Zipper",
    image: "",
    price: 999,
    category: "jacket",
    discountPercentage: "30%",
    discountPrice: 699,
    inStock: true,
    rating: 3.9,
    desc: " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
  },
  {
    _id: uuid(),
    name: "Black Oversized Zipper",
    image: "",
    price: 999,
    category: "jacket",
    discountPercentage: "30%",
    discountPrice: 699,
    inStock: true,
    rating: 3.9,
    desc: " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
  },
  {
    _id: uuid(),
    name: "Black Oversized Shacket",
    image: "",
    price: 999,
    category: "jacket",
    discountPercentage: "30%",
    discountPrice: 699,
    inStock: true,
    rating: 3.9,
    desc: " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
  },
    // SHIRTS
    {
      _id: uuid(),
      name: "Green Plaid Flannel Oversized Shirt",
      image: "",
      price: 999,
      category: "shirt",
      discountPercentage: "30%",
      discountPrice: 699,
      inStock: true,
      rating: 3.9,
      desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",

    },
    {
      _id: uuid(),
      name: "Beige Plaid Flannel Oversized Shirt",
      image: "",
      price: 999,
      category: "shirt",
      discountPercentage: "30%",
      discountPrice: 699,
      inStock: true,
      rating: 3.9,
      desc: " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",

    },
    {
      _id: uuid(),
      name: "Black & White Checkered Plaid Oversized Shirt",
      image: "",
      price: 999,
      category: "shirt",
      discountPercentage: "30%",
      discountPrice: 699,
      inStock: true,
      rating: 3.9,
      desc: " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",

    },
    {
      _id: uuid(),
      name: "Dark Navy Blue Checkered Plaid Oversized Shirt",
      image: "",
      price: 999,
      category: "shirt",
      discountPercentage: "30%",
      discountPrice: 699,
      inStock: true,
      rating: 3.9,
      desc: " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",

    },
];